# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import triton_lang_extension as tle
from flag_gems.utils.shape_utils import volume

logger = logging.getLogger(__name__)


@triton.jit
def empty_kernel(
    output_ptr,
    n_elements,
    BLOCK_SIZE: tl.constexpr,
):
    """Empty kernel that does nothing - just allocates uninitialized memory."""
    pid = tle.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    # Empty means uninitialized, so we don't write anything
    # But we need at least one store to make the kernel valid
    # Store a dummy value that the user will ignore anyway
    tl.store(output_ptr + offsets, 0.0, mask=mask)


def empty(
    size,
    *,
    dtype=None,
    layout=None,
    device=None,
    pin_memory=None,
    memory_format=None,
):
    """Returns a tensor filled with uninitialized data."""
    logger.debug("GEMS EMPTY")
    if dtype is None:
        dtype = torch.get_default_dtype()
    if device is None:
        import flag_gems.runtime as _rt

        device = torch.device(_rt.device.name)
    if layout is None:
        layout = torch.strided
    if pin_memory is None:
        pin_memory = False
    if memory_format is None:
        memory_format = torch.contiguous_format

    # Allocate via empty_strided instead of torch.empty to avoid self-recursion
    # through aten::empty.memory_format. Meta is used only to get strides for
    # the requested memory_format (compatible with PyTorch < 2.8 without
    # torch.library.get_kernel).
    shape = tuple(size)
    meta = torch.empty(shape, dtype=dtype, device="meta", memory_format=memory_format)
    out = torch.empty_strided(
        shape,
        meta.stride(),
        dtype=dtype,
        layout=layout,
        device=device,
        pin_memory=pin_memory,
    )
    # Skip triton kernel for complex dtypes — triton cannot canonicalize complex
    # pointer types on some backends, and empty() returns uninitialized memory
    # anyway so skipping the store is functionally safe for all backends.
    if dtype.is_complex:
        return out
    # NOTE: removing this zero-store looks like an easy win (~6% of decode GPU
    # time at ~3000 calls/step on DeepSeek-V4/PPU) but is NOT safe: parts of
    # the stack allocate state buffers via empty() and silently rely on this
    # kernel's zero-fill (observed: DeepSeek-V4 compressor state cache IMAs
    # with true-uninitialized memory). Any future removal must first audit
    # all empty() consumers for zero-init assumptions.
    N = volume(shape)
    grid_fn = lambda meta: (triton.cdiv(N, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(device):
        empty_kernel[grid_fn](out, N, BLOCK_SIZE=1024)
    return out
